import type { ChatConfig, ScriptLine } from './types'

/** Los 15 colores clásicos que Twitch asigna a los usuarios sin color propio. */
export const TWITCH_COLORS = [
  '#FF0000',
  '#0000FF',
  '#008000',
  '#B22222',
  '#FF7F50',
  '#9ACD32',
  '#FF4500',
  '#2E8B57',
  '#DAA520',
  '#D2691E',
  '#5F9EA0',
  '#1E90FF',
  '#FF69B4',
  '#8A2BE2',
  '#00FF7F',
]

export const DEFAULT_SCRIPT: ScriptLine[] = [
  { id: 's1', user: 'nahirGamer', text: 'buenas noches gente!! 🎉', badges: ['sub'] },
  { id: 's2', user: 'ElTanoStream', text: 'primeraaaa', badges: [] },
  { id: 's3', user: 'moderadorx', text: 'bienvenidos al directo, respeten el chat', badges: ['mod'] },
  { id: 's4', user: 'lupita_ok', text: 'que grande ese clutch', badges: ['vip'] },
  { id: 's5', user: 'pepito99', text: 'KEKW no puedo con esto', badges: [] },
  { id: 's6', user: 'streamerLatam', text: 'dale un follow que es gratis ❤️', badges: ['broadcaster'] },
  { id: 's7', user: 'juanchoo', text: 'vengo del clip de tiktok jajaja', badges: ['prime'] },
  { id: 's8', user: 'sofiPlays', text: 'alguien mas escucha el eco?', badges: [] },
  { id: 's9', user: 'darkNight_', text: 'GG WP', badges: ['sub'] },
  { id: 's10', user: 'marto_arg', text: 'se viene el subathon?? 👀', badges: [] },
]

export const RANDOM_USERS = [
  'nahirGamer', 'ElTanoStream', 'lupita_ok', 'pepito99', 'juanchoo', 'sofiPlays',
  'darkNight_', 'marto_arg', 'kevin_tv', 'laFlaca', 'zeroCooL', 'mateo__',
  'valen_streams', 'ChinoCba', 'agusHD', 'MartinaGG', 'tomi_ok', 'rocioLive',
  'nachoDev', 'CamilaXD', 'BrunoPlay', 'facuu', 'lauta_', 'gonzaTV',
  'PipaBoss', 'micaela_', 'santi_ok', 'JuliPro', 'ferchuu', 'EmiRush',
]

export const RANDOM_MESSAGES = [
  'buenas gente!!',
  'primeraaaa',
  'KEKW',
  'que grande ese clutch',
  'jajajaja no puedo',
  'vamos que se puede 💪',
  'alguien mas tiene lag?',
  'PogChamp',
  'se escucha re bien hoy',
  'dale follow que es gratis',
  'LULW',
  'que juego es este?',
  'vengo del clip de tiktok',
  'GG WP',
  'se viene el subathon?? 👀',
  'literal el mejor stream de la noche',
  'F',
  'no way 😳',
  'sube el volumen del juego porfa',
  'ese emote es nuevo?',
  'holaaa desde argentina 🇦🇷',
  'holaaa desde mexico 🇲🇽',
  'holaaa desde españa 🇪🇸',
  'me quedo hasta el final',
  'crack total',
  'nooooo justo ahi',
  'que racha increible',
  'PepeLaugh',
  'buenardo',
  'te seguí en insta tambien',
  'primera vez que caigo, muy bueno',
  'monkaS',
  'esto va directo a clips',
  'sos un fenomeno',
  'chat, comportense 😂',
]

export const DEFAULT_CONFIG: ChatConfig = {
  v: 1,

  width: 480,
  height: 720,
  previewBg: 'checker',

  layout: 'bubble',
  direction: 'bottom',
  align: 'left',
  gap: 8,
  padX: 14,
  padY: 10,
  radius: 12,
  maxWidth: 100,
  fitContent: true,
  nameOnOwnLine: false,

  fontFamily: 'Inter',
  fontSize: 22,
  fontWeight: 600,
  lineHeight: 1.35,
  letterSpacing: 0,
  textColor: '#FFFFFF',
  usernameColorMode: 'twitch',
  usernameColor: '#9146FF',
  usernameWeight: 800,
  uppercaseName: false,
  showColon: true,

  outlineWidth: 0,
  outlineColor: '#000000',
  shadowBlur: 4,
  shadowColor: '#000000',

  bgColor: '#18181B',
  bgOpacity: 85,
  borderWidth: 0,
  borderColor: '#9146FF',
  boxShadow: 0,
  boxShadowColor: '#000000',

  showBadges: true,
  badgeSize: 18,

  perspective: 800,
  rotateX: 0,
  rotateY: 0,
  rotateZ: 0,
  scale: 1,

  animation: 'slide-left',
  animationDuration: 350,
  fadeOutAfter: 0,
  maxMessages: 12,
  messageInterval: 1800,
  intervalJitter: 60,

  liveSync: true,

  source: 'random',
  twitchChannel: '',
  hideCommands: true,
  blockedUsers: 'nightbot, streamelements, streamlabs, moobot, fossabot',
  script: DEFAULT_SCRIPT,
  loopScript: true,
}
